config/routes.rb
Rails.application.routes.draw do

  get "about", to: "about#index"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "session#new"
  post "sign_in", to: "session#create"

  delete "logout", to: "session#destroy"

  get "password/reset", to: "passwords#new" 
  post "password/reset", to: "passwords#create"

  get "password/reset/edit", to: "passwords_reset#edit" 
  patch "password/reset/edit", to: "passwords_reset#update"

  get "/auth/twitter/callback", to: "omniauth_callback#twitter"

  resources :twitter_accounts
  resources :tweets

  root to: "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account

  validates :body, length: {minimum: 1, maximum: 280}
  validates :publish_at, presence: true

  # Scopes
  default_scope {order(created_at: :desc)}

  after_initialize do
    self.publish_at ||= 24.hours.from_now
  end

  after_save_commit do
    if publish_at_previously_changed?
      TweetJob.set(wait_until: publish_at).perform_later(self)
    end
  end

  def published?
    tweet_id?
  end

  def publish_to_twitter!
    tweet = twitter_account.client.post("tweets", "{\"text\":\"#{body}\"}")
    update(tweet_id: tweet['data']['id'])
  end

end

app/models/twitter_account.rb
class TwitterAccount < ApplicationRecord
  has_many :tweets, dependent: :destroy
  
  belongs_to :user

  validates :username, uniqueness: true

  require "x"

  def client
    x_credentials = {
      api_key:             Rails.application.credentials.dig(:twitter, :api_key),
      api_key_secret:      Rails.application.credentials.dig(:twitter, :api_secret),
      access_token:        token,
      access_token_secret: secret,
    }

    X::Client.new(**x_credentials)
  end
end

app/models/user.rb
#email: string
#password_digest: string
#
#password:string virtual
#password_confirmation: string virtual

class User < ApplicationRecord

    has_many :twitter_accounts
    has_many :tweets

    has_secure_password

    validates :email, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

    def index
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :set_current_user

    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end

    def require_user_loggged_in!
        redirect_to sign_in_path, alert: "You must be singed in" if Current.user.nil?
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
end

app/controllers/omniauth_callback_controller.rb
class OmniauthCallbackController < ApplicationController
    def twitter
        twitter_account = Current.user.twitter_accounts.where(username: auth.info.nickname).first_or_initialize
        twitter_account.update(
            name: auth.info.name,
            image: auth.info.image,
            token: auth.credentials.token,
            secret: auth.credentials.secret
        )

        redirect_to twitter_accounts_path, notice: "Successfully connected to twitter"
    end

    def auth
        request.env['omniauth.auth']
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :require_user_loggged_in!, only: [:edit, :update] 

    def edit
    end

    def update
        if Current.user.update(password_params)
            redirect_to root_path, notice: "Password updated!"
        else
            render :edit
        end
    end

    def new
    end

    def create
        @user = User.find_by(email: params[:email])

        if @user.present?
            #send the email
            PasswordMailer.with(user: @user).reset.deliver_now
            redirect_to root_path, notice: "If an account with the email is found, we have sent the instruction to reset password"
        else
            redirect_to root_path, notice: "If an account with the email is found, we have sent the instruction to reset password"
        end
    end

    private
    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/passwords_reset_controller.rb
class PasswordsResetController < ApplicationController
    def edit
        @user = User.find_signed!(params[:token], purpose: "password_reset")
    rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to sign_in_path, alert: "Your token has expired, please try again"
    end

    def update
        @user = User.find_signed!(params[:token], purpose: "password_reset")

        if @user.update(password_params)
            redirect_to sign_in_path, notice: "Your password reset successfully, please sign in."
        else
            render :edit
        end
    end

    private
    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

    def new
        @user = User.new
    end

    def create
        # binding.pry
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Seccussfully created account"
        else
            render :new
        end
    end

    private
    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

    def new
    end

    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Logged in successfully"
        else
            flash[:alert] = "Invalid email or password"
            render :new
        end
    end
    
    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "logged out"
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :require_user_loggged_in!
    before_action :set_tweet, only: [:edit, :update, :destroy]

    def index
        @tweets = Current.user.tweets
    end

    def new
        @tweet = Tweet.new
    end

    def create
        @tweet = Current.user.tweets.new(tweet_params)
        if @tweet.save
            redirect_to tweets_path, notice: "Tweet scheduled successfully"
        else
            render :new
        end
    end

    def update
        if @tweet.update(tweet_params)
            redirect_to tweets_path, notice: "Tweet was updated successfully"
        else
            render :edit
        end
    end

    def edit
    end

    def destroy
        if @tweet.destroy
            redirect_to tweets_path, notice: "Tweet was unscheduled successfully"
        else
            render :edit
        end
    end

    private
    def tweet_params
        params.require(:tweet).permit(:twitter_account_id, :body, :publish_at)
    end

    def set_tweet
        @tweet = Current.user.tweets.find(params[:id])
    end


end

app/controllers/twitter_accounts_controller.rb
class TwitterAccountsController < ApplicationController
    before_action :require_user_loggged_in!
    before_action :set_twitter_account, only: [:destroy]

    def index
        @twitter_accounts = Current.user.twitter_accounts
    end

    def destroy
        @twitter_accounts.destroy
        redirect_to twitter_accounts_path, notice: "Successfully disconnected twitter account @#{@twitter_accounts.username}"
    end

    private

    def set_twitter_account
        @twitter_accounts = Current.user.twitter_accounts.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1> About Us </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduledTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <style>
    .body-bg-color {
      background-color: #FFFBF5;
      }
  </style>

  <body class="body-bg-color">
    <%= render partial: "shared/navbar" %>
    <div class="container">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center mt-5">
    <h1>Welcome to Scheduled Tweets </h1>
</div>

app/views/passwords_reset/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card shadow-lg p-3 mb-5 bg-body-tertiary rounded" style="max-width: 600px;">
        <div class="card-body">
          <h1 class="card-title">Reset Password</h1>
          <%= form_with model: @user, url: password_reset_edit_path(token: params[:token]), data: { turbo: false } do |form| %>
            <% if form.object.errors.any? %>
              <div class="alert alert-danger">
                <% form.object.errors.full_messages.each do |message| %>
                  <div><%= message %></div>
                <% end %>
              </div>
            <% end %>

            <div class="mb-3">
              <%= form.label :password %>
              <%= form.password_field :password, class: "form-control", placeholder: "New Password" %>
            </div>

            <div class="mb-3">
              <%= form.label :password_confirmation %>
              <%= form.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Password" %>
            </div>

            <div class="mb-3">
              <%= form.submit "Reset Password", class: "btn btn-dark btn-block" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/session/new.html.erb
<div class="container">
  <div class="row justify-content-end">
    <div class="col-md-6">
      <div class="card shadow-lg p-3 mb-5 bg-body-tertiary rounded">
        <div class="card-body">
          <h1 class="card-title mb-4">Sign In</h1>

          <%= form_with url: sign_in_path, data: { turbo: false } do |form| %>
            <div class="mb-4">
              <%= form.label :email %>
              <%= form.text_field :email, class: "form-control", placeholder: "bharat@gmail.com" %>
            </div>

            <div class="mb-5">
              <%= form.label :password %>
              <%= form.password_field :password, class: "form-control", placeholder: "password" %>
              <%= link_to "Forgot your password?", password_reset_path, class: "text-muted" %>
            </div>

            <div class="mb-3">
              <%= form.submit "Sign In", class: "btn btn-dark btn-block"%>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-warning mt-4" role="alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_form_error.html.erb
<% if form.object.errors.any? %>
        <div class="alert alert-danger">
            <% form.object.errors.full_messages.each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg nav-bg-color shadow-lg p-3 mb-5">
  <div class="container-fluid">
    <%= link_to "Home", root_path, class: "navbar-brand text-white fw-bold fs-3" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
    <% if Current.user %>
      <ul class="navbar-nav">
        <li class="nav-item">
         <%= link_to "Tweets", tweets_path, class: "nav-link fw-semibold fs-6 text-white" %>
        </li>
        <li class="nav-item">
         <%= link_to "Twitter Accounts", twitter_accounts_path, class: "nav-link fw-semibold fs-6 text-white" %>
        </li>
      </ul>
      <% end %>

      <ul class="navbar-nav ms-auto mb-2 mb-lg-0" >
        <% if Current.user%>
          <li class="nav-item">
            <%= link_to Current.user.email, edit_password_path, class: "nav-link fw-semibold fs-6 text-white" %>
          </li>
          <li class="nav-item">
            <%= button_to "logout", logout_path, method: :delete, class: "btn btn-outline-danger fw-semibold fs-6 text-white" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", sign_up_path, class: "nav-link fw-semibold fs-6 text-white"%>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In", sign_in_path, class: "nav-link fw-semibold fs-6 text-white"%>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>


<style>
  .nav-bg-color {
    background-color: #18122B;
  }
</style>

app/views/tweets/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8", style="max-width: 700px;">
      <div class="card shadow-lg p-3 mb-5 bg-body-tertiary rounded">
        <div class="card-body">
        <h1 class="card-title">Schedule Tweets</h1>
          <%= form_with model: @tweet, data: { turbo: false } do |form| %>
            <%= render partial: "shared/form_error", locals: { form: form } %>

            <div class="mb-3">
              <%= form.label :twitter_account_id %>
              <%= form.collection_select :twitter_account_id, Current.user.twitter_accounts, :id, :username, {}, { class: "form-control" } %>
              <%= link_to "Connect your Twitter Account", "/auth/twitter", method: :post, data: { turbo: false } %>
            </div>

            <div class="mb-3">
              <%= form.label :body %>
              <%= form.text_area :body, class: "form-control" %>
            </div>

            <div class="mb-3">
              <%= form.label :publish_at %>
              <div class="form-control">
                <%= form.datetime_select :publish_at %>
              </div>
            </div>

            <div class="mb-3">
              <%= form.button "Schedule", class: "btn btn-dark" %>
              <% if form.object.persisted? %>
                <%= link_to "Delete", form.object, method: :delete, data: { confirm: "Are you sure you want to unschedule this tweet?" }, class: "btn btn-danger" %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tweets/_tweet.html.erb
<div class="container d-flex justify-content-center mt-5">
  <div class="mb-4 card card-body shadow-lg p-3 mb-5 bg-body-tertiary rounded" style="max-width: 700px;">
    <div class="d-flex flex-column">
        <div class="d-flex align-items-center shadow-sm p-3 mb-5 bg-body-gray rounded card-header ">
            <%= image_tag tweet.twitter_account.image, class: "rounded-circle me-2", style: "max-width: 40px; max-height: 40px;" %>
        
            <div class="fw-bold text-dark">
                <%= tweet.twitter_account.name %>
            </div>
            <%= link_to "@#{tweet.twitter_account.username}", "https://twitter.com/#{tweet.twitter_account.username}", target: :_blank, class: "text-secondary text-decoration-none" %>

        </div>
        <div class="mb-3">
            <%= tweet.body %>
        </div>

        <% if tweet.published? %>
        <div class="mb-3">
          <%= link_to "View Tweet", "https://twitter.com/#{tweet.twitter_account.username}/status/#{tweet.tweet_id}", target: :_blank, class: "btn btn-dark" %>
        </div>
        <% else %>
        <div class="mb-3">
          Scheduled for <%= l tweet.publish_at, format: :long %>
        </div>
        <div>
          <%= link_to "Edit Tweet", edit_tweet_path(tweet), class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tweets/edit.html.erb
<h1>Edit Tweet</h1>

<%= render "form", tweet: @tweet %>

app/views/tweets/index.html.erb
<div class="d-flex justify-content-between align-items-center mt-5">
    <h1>Tweets</h1>

    <% if Current.user.twitter_accounts.any?%>
        <%= link_to "Schedule a Tweet", new_tweet_path, class: "btn btn-dark mb-4"%>
    <%end%>
</div>

<% if Current.user.twitter_accounts.none?%>
    <%= button_to "Connect a Twitter Account", "/auth/twitter", method: :post, data: {turbo: false}, class: "btn btn-dark" %>
<%end%>

<%= render @tweets %>

app/views/tweets/new.html.erb
<%= render "form", tweet: @tweet %>

app/views/twitter_accounts/index.html.erb
<div class="d-flex align-items-center justify-content-between mt-5 mb-5">
    <h1>Twitter Accounts </h1>
    <%= button_to "Connect a Twitter Account", "/auth/twitter", method: :post, data: {turbo: false}, class: "btn btn-dark" %>
</div>

<% @twitter_accounts.each do |twitter_account|%>
    <div class="card card-body bg-body-tertiary rounded shadow-lg p-3 mb-5 rounded card-header", style="max-width: 400px;">
            <div class="d-flex align-items-center justify-content-evenly mb-4">
                <div class="me-4">
                    <%= image_tag twitter_account.image, class: "rounded-circle" %>
                    <%= link_to "@#{twitter_account.username}", "https://twitter.com/#{twitter_account.username}", target: :_blank %>
                </div>

                <%= button_to "Disconnet", twitter_account, method: :delete, form: { data: { turbo_confirm: "If you disconnect all the unpublished tweets will be deleted and cannot be post. Are you sure you want disconnect?" } }, class: "btn btn-danger" %>
            </div>
    </div>
<%end%>